chore: init commit
Informasjonsforvaltning/fdk-event-streaming-service pull request #1
Opened 2022-03-21 11:18 UTC by jeffreiffers

2022-03-29 14:11 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +#      - name: Notify slack
Huske å kommentere inn igjen. For å få med evt fails, så burde det kanskje gå en slack-melding pr matrix app.

2022-03-29 14:15 UTC, valosnah approved these changes

2022-08-03 10:36 UTC, valosnah requested changes

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-1/values/demo.yaml
> +NAMESPACE: staging
demo

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-1/values/demo.yaml
> +KAFKA_VOLUMENAME: fdk-dev-staging-kafka-1
fdk-dev-demo-kafka-1

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-1/values/prod.yaml
> +NAMESPACE: staging
prod

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-1/values/prod.yaml
> +KAFKA_VOLUMENAME: fdk-dev-staging-kafka-1
fdk-prod-kafka-1

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-2/values/demo.yaml
> +NAMESPACE: staging
demo

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-2/values/demo.yaml
> +KAFKA_VOLUMENAME: fdk-dev-staging-kafka-2
fdk-dev-demo-kafka-2

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-2/values/prod.yaml
> +NAMESPACE: staging
prod

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-2/values/prod.yaml
> +KAFKA_VOLUMENAME: fdk-dev-staging-kafka-2
fdk-prod-kafka-2

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-3/values/demo.yaml
> +NAMESPACE: staging
demo

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-3/values/demo.yaml
> +KAFKA_VOLUMENAME: fdk-dev-staging-kafka-3
fdk-dev-demo-kafka-3

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-3/values/prod.yaml
> +KAFKA_VOLUMENAME: fdk-dev-staging-kafka-3
fdk-prod-kafka-3

2022-08-03 10:36 UTC, valosnah commented on helm-sources/kafka-3/values/prod.yaml
> +NAMESPACE: staging
prod

2022-08-03 10:36 UTC, valosnah commented on helm-sources/schema-registry-1/values/demo.yaml
> +NAMESPACE: staging
demo

2022-08-03 10:36 UTC, valosnah commented on helm-sources/schema-registry-1/values/prod.yaml
> +NAMESPACE: staging
prod

2022-08-03 10:36 UTC, valosnah commented on helm-sources/schema-registry-2/values/demo.yaml
> +NAMESPACE: staging
demo

2022-08-03 10:36 UTC, valosnah commented on helm-sources/schema-registry-2/values/prod.yaml
> +NAMESPACE: staging
prod

2022-08-03 10:36 UTC, valosnah commented on helm-sources/zookeeper-1/values/demo.yaml
> +NAMESPACE: staging
demo

2022-08-03 10:36 UTC, valosnah commented on helm-sources/zookeeper-1/values/prod.yaml
> +NAMESPACE: staging
prod

2022-08-03 10:36 UTC, valosnah commented on helm-sources/zookeeper-2/values/demo.yaml
> +NAMESPACE: staging
Trengs helm for zookeeper2? Vi skulle vel bare starte med 1 instans?
If so, namespace=demo
volumename=fdk-dev-demo-zookeeper-2

2022-08-03 10:36 UTC, valosnah commented on helm-sources/zookeeper-2/values/prod.yaml
> +NAMESPACE: staging
Se kommentar for demo

2022-08-03 10:36 UTC, tenstad approved these changes

2022-08-03 10:36 UTC, tenstad commented on README.md
> +- Kafka 2 (broker 2)
```suggestion
- Kafka 2 (broker 2)
- Kafka 3 (broker 3)
```

2022-08-03 10:36 UTC, tenstad commented on README.md
> +- Zookeeper 2
```suggestion
- Zookeeper 2
- Schema registry 1
- Schema registry 2
```

2022-08-03 10:36 UTC, tenstad commented on docker-compose.yml
> +        while [ 1 -eq 1 ];do sleep 60;done
\n @ EOF
```suggestion
        while [ 1 -eq 1 ];do sleep 60;done

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/templates/namespace.yaml
> +  name: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
\n @ EOF
```suggestion
  name: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/templates/service.yaml
> +  loadBalancer: {}
Fjern status og legg til \n @ EOF
```suggestion

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/Chart.yaml
> +home: https://github.com/Informasjonsforvaltning/fdk-event-streaming-service
\n @ EOF
```suggestion
home: https://github.com/Informasjonsforvaltning/fdk-event-streaming-service

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/templates/service.yaml
> +  creationTimestamp: null
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/templates/stateful-set.yaml
> +  creationTimestamp: null
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/templates/stateful-set.yaml
> +
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/templates/storage.yaml
> +  creationTimestamp: null
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/templates/storage.yaml
> +status: {}
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/values/demo.yaml
> +  staging.yaml#namespace
Noe feil her?

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/values/demo.yaml
> +KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"
\n @ EOF
```suggestion
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/values/prod.yaml
> +  staging.yaml#namespace
Noe feil her?

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-1/values/staging.yaml
> +KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"
\n @ EOF
```suggestion
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/templates/service.yaml
> +  creationTimestamp: null
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/Chart.yaml
> +home: https://github.com/Informasjonsforvaltning/fdk-event-streaming-service
\n @ EOF
```suggestion
home: https://github.com/Informasjonsforvaltning/fdk-event-streaming-service

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/templates/namespace.yaml
> +  name: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
\n @ EOF
```suggestion
  name: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/templates/service.yaml
> +  loadBalancer: {}
Fjerne status
\n @ EOF
```suggestion

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/templates/stateful-set.yaml
> +  creationTimestamp: null
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/templates/stateful-set.yaml
> +  replicas: 1
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/templates/storage.yaml
> +  creationTimestamp: null
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/templates/storage.yaml
> +status: {}
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/values/demo.yaml
> +  staging.yaml#namespace
Noe feil her?

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/values/demo.yaml
> +KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"
\n @ EOF
```suggestion
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/values/prod.yaml
> +  staging.yaml#namespace
Noe feil her?

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/values/prod.yaml
> +KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "3"
\n @ EOF
```suggestion
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "3"

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-2/values/staging.yaml
> +KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"
\n @ EOF
```suggestion
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/Chart.yaml
> +home: https://github.com/Informasjonsforvaltning/fdk-event-streaming-service
\n @ EOF
```suggestion
home: https://github.com/Informasjonsforvaltning/fdk-event-streaming-service

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/templates/namespace.yaml
> +  name: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
\n @ EOF
```suggestion
  name: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
  
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/templates/service.yaml
> +  loadBalancer: {}
Fjerne status
\n @ EOF
```suggestion

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/templates/service.yaml
> +  creationTimestamp: null
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/templates/stateful-set.yaml
> +  creationTimestamp: null
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/templates/stateful-set.yaml
> +  replicas: 1
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/templates/storage.yaml
> +status: {}
```suggestion
```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/values/demo.yaml
> +  staging.yaml#namespace
Noe feil her?

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/values/demo.yaml
> +KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"
\n @ EOF
```suggestion
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"

```

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/values/prod.yaml
> +  staging.yaml#namespace
Noe feil her?

2022-08-03 10:36 UTC, tenstad commented on helm-sources/kafka-3/values/prod.yaml
> +KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "3"
\n @ EOF
```suggestion
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "3"

```

2022-08-03 11:12 UTC, valosnah requested changes

2022-08-03 11:12 UTC, valosnah commented on helm-sources/kafka-3/templates/storage.yaml
> +    app: kafka-2
kafka-3

2022-08-03 11:12 UTC, valosnah commented on helm-sources/kafka-3/templates/storage.yaml
> +  name: kafka-2-claim0
kafka-3-claim0

2022-08-03 11:17 UTC, valosnah approved these changes

2022-08-03 11:19 UTC, merged

2022-08-03 11:39 UTC, tenstad commented on helm-sources/zookeeper-2/templates/namespace.yaml
> +  name: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
Trenger vel ikke namespace ressurs per zookeeper?

2022-08-03 11:41 UTC, tenstad commented on helm-sources/zookeeper-2/templates/storage.yaml
> +  name: {{ required "Missing value ZOOKEEPER_VOLUMENAME" .Values.ZOOKEEPER_VOLUMENAME }}
Kolliderer vel med PV i `helm-sources/zookeeper-1/templates/storage.yaml`

2022-08-03 11:45 UTC, tenstad commented on helm-sources/schema-registry-2/templates/stateful-set.yaml
> +            value: { { required "Missing value SCHEMA_REGISTRY_BOOTSTRAP_SERVERS" .Values.SCHEMA_REGISTRY_BOOTSTRAP_SERVERS } }
```suggestion
            value: {{ required "Missing value SCHEMA_REGISTRY_BOOTSTRAP_SERVERS" .Values.SCHEMA_REGISTRY_BOOTSTRAP_SERVERS }}
```

2022-08-03 11:45 UTC, tenstad commented on helm-sources/kafka-3/templates/stateful-set.yaml
> +            value: { { required "Missing value KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR" .Values.KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR | quote } }
```suggestion
            value: {{ required "Missing value KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR" .Values.KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR | quote }}
```

2022-08-03 11:46 UTC, tenstad commented on helm-sources/kafka-2/templates/stateful-set.yaml
> +            value: { { required "Missing value KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR" .Values.KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR | quote } }
```suggestion
            value: {{ required "Missing value KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR" .Values.KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR | quote }}
```

2022-08-03 11:48 UTC, tenstad commented on docker-compose.yml
> +        while [ 1 -eq 1 ];do sleep 60;done
```suggestion
        while true; do sleep 60; done
```

2022-08-03 11:49 UTC, tenstad commented on docker-compose.yml
> +      - "8081:8081"
Samme format som `kafka`, uten `"`
```suggestion
      - 8081:8081
```

2022-08-03 11:49 UTC, tenstad commented on README.md
> +- Kafka 2 (broker 3, prod only)
```suggestion
- Kafka 3 (broker 3, prod only)
```